import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto';
import WebSocket from 'ws';

export const DEFAULT_NOSTR_RELAYS = Object.freeze(['wss://relay.damus.io', 'wss://nos.lol', 'wss://relay.primal.net']);
const MAX_SIGNAL_BYTES = 48 * 1024;
const KIND = 20000;
const DEFAULT_TTL_MS = 30_000;
// Relay operation timeout is intentionally separate from human approval lifetime.
const DEFAULT_SESSION_TTL_MS = 10 * 60_000;
function roomTag(inviteId) { if (typeof inviteId !== 'string' || !/^[0-9a-f-]{16,}$/i.test(inviteId)) throw new Error('PAIRING_INVITE_ID_INVALID'); return createHash('sha256').update(`dsh-pair:${inviteId}`).digest('hex').slice(0, 32); }
function keyBytes(value) { if (Buffer.isBuffer(value) && value.length === 32) return value; if (typeof value === 'string') { const decoded = Buffer.from(value, 'base64url'); if (decoded.length === 32) return decoded; } throw new Error('NOSTR_SIGNAL_KEY_REQUIRED'); }
export function encryptNostrSignal(value, sessionKey) {
  const nonce = randomBytes(12); const c = createCipheriv('aes-256-gcm', keyBytes(sessionKey), nonce); const body = Buffer.concat([c.update(JSON.stringify(value), 'utf8'), c.final()]); return `${nonce.toString('base64url')}.${c.getAuthTag().toString('base64url')}.${body.toString('base64url')}`; }
export function decryptNostrSignal(value, sessionKey) { try { const [iv, tag, body] = String(value).split('.'); if (!iv || !tag || !body) return null; const d = createDecipheriv('aes-256-gcm', keyBytes(sessionKey), Buffer.from(iv, 'base64url')); d.setAuthTag(Buffer.from(tag, 'base64url')); return JSON.parse(Buffer.concat([d.update(Buffer.from(body, 'base64url')), d.final()]).toString('utf8')); } catch { return null; } }
function open(url, Impl, timeoutMs = 8000) { return new Promise((resolve, reject) => { let settled = false; const ws = new Impl(url); const finish = (error) => { if (settled) return; settled = true; clearTimeout(timer); error ? reject(error) : resolve(ws); }; const fail = (e) => finish(e instanceof Error ? e : new Error('NOSTR_SIGNAL_CONNECT_FAILED')); const timer = setTimeout(() => { try { ws.close(); } catch {} finish(new Error('NOSTR_SIGNAL_CONNECT_TIMEOUT')); }, timeoutMs); timer.unref?.(); ws.once('open', () => finish()); ws.once('error', fail); }); }
function send(ws, packet) { return new Promise((resolve, reject) => { if (ws.readyState !== ws.OPEN && ws.readyState !== WebSocket.OPEN) return reject(new Error('NOSTR_SIGNAL_UNAVAILABLE')); try { ws.send(packet, (error) => error ? reject(error) : resolve()); } catch (error) { reject(error); } }); }
/** Public Nostr mailbox for encrypted, short-lived Offer/Answer only. */
export async function startNostrSignal({ inviteId, sessionKey, relays = DEFAULT_NOSTR_RELAYS, role, onSignal, onError, signEvent, WebSocketImpl = WebSocket, timeoutMs = 8000, ttlMs = DEFAULT_TTL_MS, sessionTtlMs = DEFAULT_SESSION_TTL_MS } = {}) {
  if (!['host', 'client'].includes(role) || typeof onSignal !== 'function') throw new Error('NOSTR_SIGNAL_OPTIONS_INVALID');
  if (typeof signEvent !== 'function') throw new Error('NOSTR_SIGNAL_SIGNER_REQUIRED');
  const tag = roomTag(inviteId); keyBytes(sessionKey); if (!Number.isSafeInteger(sessionTtlMs) || sessionTtlMs <= 0) throw new Error('NOSTR_SIGNAL_SESSION_TTL_INVALID'); const sockets = await Promise.all(relays.map((url) => open(url, WebSocketImpl, timeoutMs).catch(() => null))); const active = sockets.filter(Boolean); if (!active.length) throw new Error('NOSTR_SIGNAL_UNAVAILABLE');
  let closed = false; let sequence = 0; const seenNonces = new Set(); const seenEvents = new Set(); const highest = { host: 0, client: 0 }; const subId = `dsh-${randomBytes(8).toString('hex')}`;
  const handle = (raw) => { try { const msg = JSON.parse(Buffer.isBuffer(raw) ? raw.toString('utf8') : String(raw)); if (msg[0] !== 'EVENT' || !msg[2] || msg[2].kind !== KIND || !Array.isArray(msg[2].tags) || !msg[2].tags.some((t) => t[0] === 'd' && t[1] === tag)) return; const event = msg[2]; if (seenEvents.has(event.id)) return; const payload = decryptNostrSignal(event.content, sessionKey); const now = Date.now(); const valid = payload && payload.session === tag && (payload.role === 'host' || payload.role === 'client') && payload.role !== role && Number.isSafeInteger(payload.seq) && payload.seq > 0 && typeof payload.nonce === 'string' && payload.nonce.length >= 16 && Number.isSafeInteger(payload.expiresAt) && payload.expiresAt >= now && payload.expiresAt <= now + 5 * 60_000; if (!valid || seenNonces.has(payload?.nonce) || payload.seq <= highest[payload.role]) return; seenEvents.add(event.id); seenNonces.add(payload.nonce); highest[payload.role] = payload.seq; Promise.resolve(onSignal(payload.signal, { role: payload.role, seq: payload.seq, eventId: event.id })).catch((error) => { try { onError?.(error); } catch {} }); } catch (error) { try { onError?.(error); } catch {} } };
  for (const ws of active) { ws.on('message', handle); await send(ws, JSON.stringify(['REQ', subId, { kinds: [KIND], '#d': [tag], limit: 8 }])); }
  const publish = async (signal) => { if (closed) throw new Error('NOSTR_SIGNAL_CLOSED'); const payload = { session: tag, role, seq: ++sequence, nonce: randomBytes(16).toString('base64url'), expiresAt: Date.now() + ttlMs, signal }; const content = encryptNostrSignal(payload, sessionKey); if (Buffer.byteLength(content) > MAX_SIGNAL_BYTES) throw new Error('NOSTR_SIGNAL_TOO_LARGE'); const event = await signEvent({ kind: KIND, created_at: Math.floor(Date.now() / 1000), tags: [['d', tag], ['t', 'dsh-pair']], content }); if (!event || typeof event !== 'object' || typeof event.id !== 'string' || typeof event.pubkey !== 'string' || typeof event.sig !== 'string') throw new Error('NOSTR_SIGNAL_EVENT_INVALID');
    const packet = JSON.stringify(['EVENT', event]); let resolved = false; let okCount = 0; let firstError = 'NOSTR_SIGNAL_REJECTED'; return new Promise((resolve, reject) => { const finish = (error, value) => { if (resolved) return; resolved = true; clearTimeout(timer); error ? reject(error) : resolve(value); }; const timer = setTimeout(() => finish(new Error('NOSTR_SIGNAL_TIMEOUT')), timeoutMs); const listener = (raw) => { try { const msg = JSON.parse(Buffer.isBuffer(raw) ? raw.toString('utf8') : String(raw)); if (msg[0] !== 'OK' || msg[1] !== event.id) return; if (msg[2] === true) finish(null, { relays: 1, eventId: event.id }); else { okCount++; firstError = typeof msg[3] === 'string' ? msg[3] : firstError; if (okCount >= active.length) finish(new Error(`NOSTR_SIGNAL_REJECTED:${firstError}`)); } } catch {} }; active.forEach((ws) => ws.on('message', listener)); Promise.allSettled(active.map((ws) => send(ws, packet))).then((results) => { const failed = results.filter((r) => r.status === 'rejected').length; if (failed >= active.length) finish(new Error('NOSTR_SIGNAL_UNAVAILABLE')); }); });
  };
  const close = () => { if (closed) return; closed = true; for (const ws of active) { try { ws.send(JSON.stringify(['CLOSE', subId])); ws.close(); } catch {} } }; const timer = setTimeout(close, sessionTtlMs); timer.unref?.(); return { tag, relays: active.length, publish, close: () => { clearTimeout(timer); close(); } };
}
export async function probeNostrRelay(url, { fetchImpl = globalThis.fetch, timeoutMs = 5000 } = {}) { if (typeof fetchImpl !== 'function') throw new Error('NOSTR_PROBE_FETCH_UNAVAILABLE'); const response = await fetchImpl(url.replace(/^wss:/, 'https:').replace(/^ws:/, 'http:'), { headers: { Accept: 'application/nostr+json' }, signal: AbortSignal.timeout(timeoutMs) }); if (!response.ok) throw new Error(`NOSTR_RELAY_HTTP_${response.status}`); return response.json(); }
